project:
  type: website

website:
  title: "blog"
  site-url: https://futz.zone
  repo-url: https://github.com/bongovanfifi/blog
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/bongovanfifi

format:
  html:
    # number-sections: false
    # toc: true
    theme:
      light: custom-light.scss
      dark: custom-dark.scss
    css: styles.css


